version: '3.3'

networks:
  frontend:
    ipam:
      config:
        - subnet: @NODE_IP_PREFIX@.0/24
services:
  meta1:
    image: @IMAGE_NAME@
    ports:
      - "34601"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./meta1/data:/pegasus/data
    command:
      - meta
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.11
    restart: on-failure
  meta2:
    image: @IMAGE_NAME@
    ports:
      - "34601"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./meta2/data:/pegasus/data
    command:
      - meta
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.12
    restart: on-failure
  replica1:
    image: @IMAGE_NAME@
    ports:
      - "34801"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./replica1/data:/pegasus/data
      - ./replica1/slog:/pegasus/slog
    command:
      - replica
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.21
    restart: on-failure
  replica2:
    image: @IMAGE_NAME@
    ports:
      - "34801"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./replica2/data:/pegasus/data
      - ./replica2/slog:/pegasus/slog
    command:
      - replica
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.22
    restart: on-failure
  replica3:
    image: @IMAGE_NAME@
    ports:
      - "34801"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./replica3/data:/pegasus/data
      - ./replica3/slog:/pegasus/slog
    command:
      - replica
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.23
    restart: on-failure
  replica4:
    image: @IMAGE_NAME@
    ports:
      - "34801"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./replica4/data:/pegasus/data
      - ./replica4/slog:/pegasus/slog
    command:
      - replica
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.24
    restart: on-failure
  replica5:
    image: @IMAGE_NAME@
    ports:
      - "34801"
    volumes:
      - ./config.ini:/pegasus/bin/config.ini:ro
      - ./replica5/data:/pegasus/data
      - ./replica5/slog:/pegasus/slog
    command:
      - replica
    privileged: true
    networks:
      frontend:
        ipv4_address: @NODE_IP_PREFIX@.25
    restart: on-failure
